export default function MetricsGuide() {
  return <section aria-labelledby="metrics-title" className="space-y-5">
    <div><h2 id="metrics-title" className="text-2xl font-semibold">What makes a better model?</h2><p className="mt-2 text-slate-400">Use RMSE first. Read MAE and R² alongside it.</p></div>
    <div className="grid gap-4 md:grid-cols-3">
      <article className="rounded-xl border border-blue-500/50 bg-blue-950/30 p-5"><p className="text-xs font-bold tracking-wider text-blue-300">MAIN SCORE · LOWER IS BETTER</p><h3 className="mt-3 text-2xl font-bold">RMSE</h3><p className="mt-2 text-sm text-slate-300">Root Mean Squared Error. Gives larger pricing mistakes more weight.</p><p className="mt-3 text-sm text-slate-400">In INR lakhs. Useful when a large overpricing or underpricing error matters. Luxury cars can have a strong effect.</p></article>
      <article className="rounded-xl border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-bold tracking-wider text-emerald-300">SUPPORTING · LOWER IS BETTER</p><h3 className="mt-3 text-2xl font-bold">MAE</h3><p className="mt-2 text-sm text-slate-300">Mean Absolute Error. The average size of the prediction error.</p><p className="mt-3 text-sm text-slate-400">MAE = 1.5 lakhs means an average absolute error of INR 150,000.</p></article>
      <article className="rounded-xl border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-bold tracking-wider text-violet-300">SUPPORTING · HIGHER IS BETTER</p><h3 className="mt-3 text-2xl font-bold">R²</h3><p className="mt-2 text-sm text-slate-300">Compares squared error with predicting the evaluation-set mean.</p><p className="mt-3 text-sm text-slate-400">1 is perfect; 0 matches that baseline; negative is worse. R² = 0.85 does not mean 85% of cars were predicted correctly.</p></article>
    </div>
    <details className="rounded-lg border border-slate-800 p-4 text-sm text-slate-400"><summary className="cursor-pointer font-medium text-slate-200">A small example and the comparison rule</summary><div className="mt-4 space-y-3 leading-relaxed"><p>If the absolute errors are 1, 1 and 4 lakhs, MAE = (1+1+4)/3 = 2 lakhs. RMSE = √((1²+1²+4²)/3) ≈ 2.45 lakhs. The large mistake raises RMSE more.</p><p>Select settings using RMSE on the shared validation set. Then report the frozen model’s hold-out RMSE, MAE and R². On the same hold-out, RMSE and R² give the same ranking; MAE adds another view. A single validation split is less stable than repeated cross-validation.</p><p>RMSE is a project choice, not universally the best metric. We choose it because large monetary errors matter here. <a href="https://scikit-learn.org/stable/modules/model_evaluation.html" target="_blank" rel="noreferrer" className="text-blue-300 underline">Metric definitions</a> · <a href="https://scikit-learn.org/stable/common_pitfalls.html" target="_blank" rel="noreferrer" className="text-blue-300 underline">Preprocessing and validation</a></p></div></details>
  </section>;
}
